name: '[DEV] Build, push, deploy'

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_REPOSITORY: compteurs-velo
  KEEL_FQDN: keel.velo-cite.org

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: '[DEV] Build and push Docker image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.ENV_LOCAL }} | base64 -d > .env.local
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u $ --password-stdin $DOCKER_REGISTRY
      - run: |
          IMAGE_NAME=$DOCKER_REGISTRY/${{ github.repository_owner }}/$IMAGE_REPOSITORY
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]') # to lowercase
          docker build . -t $IMAGE_NAME:dev
          docker push $IMAGE_NAME:dev
  deploy:
    needs: build
    name: '[DEV] Deploy the new image'
    runs-on: ubuntu-latest
    steps:
      - run: |
          IMAGE_NAME=$DOCKER_REGISTRY/${{ github.repository_owner }}/$IMAGE_REPOSITORY
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]') # to lowercase
          echo IMAGE_NAME=$IMAGE_NAME
          curl \
            -u admin:${{ secrets.KEEL_PASSWORD }} \
            -d "{\"name\":\"$IMAGE_NAME\", \"tag\":\"dev\"}" \
            -H "Content-Type: application/json" \
            -X POST https://$KEEL_FQDN/v1/webhooks/native
