name: '[DEV] Build, push, deploy'

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-push-deploy:
    uses: LoicGombeaud/workflows/.github/workflows/build-push-deploy.yaml@main
    with:
      image-repository: compteurs-velo-dev
      image-tags: latest
      keel-fqdn: keel.velo-cite.org
      keel-user: admin
      add-date-tag: true
    secrets:
      keel-password: ${{ secrets.KEEL_PASSWORD }}
